<?php

namespace AppBundle\Repository;

/**
 * ExamePrecoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamePrecoRepository extends \Doctrine\ORM\EntityRepository
{
}
