<?php

namespace AppBundle\Repository;

/**
 * OrdemServicioExameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdemServicioExameRepository extends \Doctrine\ORM\EntityRepository
{
}
