<?php

namespace AppBundle\Repository;

/**
 * PostoColectaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostoColectaRepository extends \Doctrine\ORM\EntityRepository
{
}
